#include <cmixconf.h>
#define yy_create_buffer ccc_create_buffer
#define yy_delete_buffer ccc_delete_buffer
#define yy_scan_buffer ccc_scan_buffer
#define yy_scan_string ccc_scan_string
#define yy_scan_bytes ccc_scan_bytes
#define yy_flex_debug ccc_flex_debug
#define yy_init_buffer ccc_init_buffer
#define yy_flush_buffer ccc_flush_buffer
#define yy_load_buffer_state ccc_load_buffer_state
#define yy_switch_to_buffer ccc_switch_to_buffer
#define yyin cccin
#define yyleng cccleng
#define yylex ccclex
#define yyout cccout
#define yyrestart cccrestart
#define yytext ccctext

#line 19 "temp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.89 96/05/25 21:02:21 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 97
#define YY_END_OF_BUFFER 98
static yyconst short int yy_accept[287] =
    {   0,
        0,    0,   98,   96,   90,   89,   77,   96,   83,   76,
       96,   71,   72,   81,   80,   68,   79,   75,   82,   35,
       35,   69,   65,   84,   70,   85,   88,   33,   73,   74,
       86,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   66,   87,   67,
       78,   90,   96,   90,   64,    0,   42,    0,   50,   59,
       51,    0,    0,   48,   56,   46,   57,   47,   58,    0,
       41,   49,   41,   35,   35,    0,   37,   36,    0,   55,
       61,   63,   62,   54,   33,   52,   33,   33,   33,   33,
       33,   33,   33,    8,   33,   33,   33,   33,   33,   33,

       16,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   53,   60,   90,    0,    0,    0,    0,   39,
       43,    0,   40,   41,    0,   37,   36,    0,   41,   38,
       38,   35,   45,   44,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   14,   33,   17,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,    0,    0,    0,    0,   41,    0,
        0,   41,   38,   38,   37,   36,   33,    1,   33,    3,
        4,   33,   33,   33,   33,   10,   11,   33,   33,   15,
       18,   33,   33,   33,   33,   33,   33,   33,   33,   33,

       33,   33,   30,   33,   33,    0,   92,    0,    0,    0,
        0,    0,   41,   38,   38,   33,    2,    5,   33,   33,
       33,   33,   13,   33,   33,   21,   33,   33,   33,   33,
       33,   33,   28,   33,   33,   32,    0,    0,    0,   33,
       33,   33,    9,   12,   33,   20,   22,   23,   24,   25,
       26,   33,   33,   33,    0,    0,   95,    0,    0,   34,
       33,    7,   33,   27,   33,   33,    0,   91,    0,   95,
       94,   34,    6,   19,   29,   31,   94,   94,   94,   94,
       94,   94,   93,   93,   93,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   29,   28,   30,   31,
       32,   32,   33,   32,   32,   34,   35,   32,   32,   32,
       32,   32,   32,   32,   36,   32,   32,   37,   32,   32,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   32,   52,   53,   54,   55,
       56,   57,   32,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[71] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    6,    6,    6,    6,    6,    6,    1,    1,    1,
        1,    6,    5,    5,    5,    5,    5,    5,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[298] =
    {   0,
        0,   69,  494,  495,   70,  495,  468,   69,  467,   68,
      452,  495,  495,  465,   64,  495,   65,   63,  464,   92,
       80,  495,  495,   61,  463,   62,  495,    0,  495,  495,
      462,  444,  424,  426,   74,   47,   43,   39,  427,   70,
      426,  434,   84,  415,  424,  422,  427,  495,   80,  495,
      495,  136,  102,  100,  495,  113,  495,  473,  495,  495,
      495,  111,  148,  495,  495,  495,  495,  495,  495,  458,
      141,  495,  144,  149,  178,  197,   96,   89,    0,  449,
      495,  495,  495,  448,    0,  495,  443,  411,  423,  410,
      425,  412,  418,  404,  405,  402,  402,  405,  402,  399,

        0,  398,  402,   71,  400,   88,  124,  404,  397,  122,
      125,  402,  495,  495,  199,   89,  200,  394,  393,  495,
      495,  208,  495,  213,  221,  119,  152,  226,  231,  495,
      495,  202,  495,  495,  415,  393,  405,  400,  388,  134,
      402,  400,  396,  388,  394,  397,    0,  383,    0,  389,
      386,  375,  377,  379,  386,  372,  370,  370,  382,  372,
      376,  380,  382,  371,  245,  365,  379,  237,  249,  257,
      262,  265,  495,  495,  148,  170,  388,    0,  368,    0,
        0,  359,  363,  347,  351,    0,    0,  338,  311,    0,
        0,  302,  302,  299,  311,  301,  305,  310,  309,  307,

      297,  302,    0,  290,  302,  345,  495,  184,  271,  291,
      297,  268,  274,  495,  495,  308,    0,    0,  289,  290,
      295,  286,    0,  280,  284,    0,  292,  289,  291,  275,
      284,  286,    0,  277,  280,    0,  295,  272,  274,  298,
      259,  239,    0,    0,  225,    0,    0,    0,    0,    0,
        0,  219,  212,  201,  300,  301,    0,  210,  306,    0,
      183,    0,  168,    0,  169,  160,  308,  495,  309,    0,
      314,    0,    0,    0,    0,    0,    0,  317,  146,  126,
       51,  321,  322,    0,  325,  495,  362,  368,  370,   74,
      376,  382,  388,  394,  400,  406,  412

    } ;

static yyconst short int yy_def[298] =
    {   0,
      286,    1,  286,  286,  286,  286,  286,  287,  286,  286,
      288,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  289,  286,  286,
      286,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  286,  286,  286,
      286,  286,  286,  286,  286,  287,  286,  287,  286,  286,
      286,  288,  288,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  290,  286,
      286,  286,  286,  286,  289,  286,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,

      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  290,  286,  286,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  291,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,

      289,  289,  289,  289,  289,  291,  286,  291,  291,  286,
      286,  286,  286,  286,  286,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  289,  292,  286,  286,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  292,  293,  294,  286,  286,  295,
      289,  289,  289,  289,  289,  289,  293,  286,  293,  294,
      296,  295,  289,  289,  289,  289,  296,  296,  296,  296,
      296,  296,  297,  297,  297,    0,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286

    } ;

static yyconst short int yy_nxt[566] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   22,   23,   24,   25,   26,   27,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   29,    4,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   28,
       40,   28,   41,   28,   28,   28,   28,   42,   43,   44,
       45,   46,   47,   28,   28,   28,   48,   49,   50,   51,
       52,   54,   52,   54,   57,   53,   60,   65,  132,   70,
       67,   71,   71,   71,   80,   81,   83,   84,   66,   68,
       69,   98,   61,   93,   99,   95,   73,   96,   75,   75,

       75,   54,   94,   54,  113,  117,   97,   58,   73,   76,
       74,   74,   75,   77,  282,   78,   90,  101,   57,  151,
      120,   76,  131,   91,  102,   77,   76,   78,   79,   92,
      152,  130,   77,  105,  106,  118,  154,  115,   76,  115,
       78,  131,  116,  107,   77,  119,  108,  114,  118,   63,
      286,   58,   78,  155,  173,   79,  130,   62,  119,   71,
       71,   71,  124,  124,  124,   73,  156,   74,   74,   75,
      122,  123,  160,  125,  123,  162,  281,  163,   76,  173,
      161,  157,  126,  214,  127,  174,  207,  122,  123,  237,
      125,  123,  182,  183,   73,   76,   75,   75,   75,  280,

      115,  126,  115,  215,  174,  116,  276,   76,  214,  127,
      128,   77,  128,   78,  275,  129,  129,  129,  165,  165,
      165,  168,  215,  168,   76,  274,  169,  169,  169,  273,
       77,  124,  124,  124,  171,  175,  171,  176,   78,  172,
      172,  172,  170,  123,  129,  129,  129,  207,  208,  129,
      129,  129,  271,  266,  175,  169,  169,  169,  265,  170,
      123,  123,  176,  209,  209,  209,  264,  169,  169,  169,
      212,  263,  212,  207,  208,  213,  213,  213,  123,  123,
      172,  172,  172,  172,  172,  172,  213,  213,  213,  209,
      209,  209,  213,  213,  213,  123,  123,  207,  262,  259,

      256,  259,  207,  268,  123,  256,  269,  259,  260,  259,
      268,  268,  123,  269,  269,  278,  260,  278,  278,  261,
      278,  123,  283,  285,  283,  285,  285,  258,  285,  257,
      254,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  207,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  279,   56,   56,   56,   56,   56,   56,   62,   62,
      223,   62,   62,   62,   85,   85,  206,  206,  206,  206,
      206,  206,  255,  255,  255,  255,  255,  255,  267,  267,
      267,  267,  267,  267,  270,  222,  270,  270,  270,  270,

      272,  272,  272,  221,  272,  272,  277,  220,  277,  277,
      277,  277,  284,  219,  284,  284,  284,  284,  218,  217,
      216,  211,  210,  205,  204,  203,  202,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  190,  189,
      188,  187,  186,  185,  184,  181,  180,  179,  178,  177,
      167,  166,  164,  159,  158,  153,  150,  149,  148,  147,
      146,  145,  144,  143,  142,  141,  140,  139,  138,  137,
      136,  135,  134,  133,  121,  286,  112,  111,  110,  109,
      104,  103,  100,   89,   88,   87,   86,   82,   72,   64,
       63,   59,   55,  286,    3,  286,  286,  286,  286,  286,

      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286
    } ;

static yyconst short int yy_chk[566] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    5,    2,    5,    8,    2,   10,   15,  290,   18,
       17,   18,   18,   18,   24,   24,   26,   26,   15,   17,
       17,   38,   10,   36,   38,   37,   21,   37,   21,   21,

       21,   54,   36,   54,   49,   53,   37,    8,   20,   21,
       20,   20,   20,   21,  281,   21,   35,   40,   56,  104,
       62,   20,   78,   35,   40,   20,   21,   20,   20,   35,
      104,   77,   21,   43,   43,  116,  106,   52,   20,   52,
       21,   78,   52,   43,   20,  116,   43,   49,   53,   62,
       63,   56,   20,  106,  126,   20,   77,   63,   53,   71,
       71,   71,   73,   73,   73,   74,  107,   74,   74,   74,
       71,   71,  110,   73,   73,  111,  280,  111,   74,  126,
      110,  107,   74,  175,   74,  127,  208,   71,   71,  208,
       73,   73,  140,  140,   75,   74,   75,   75,   75,  279,

      115,   74,  115,  176,  127,  115,  266,   75,  175,   74,
       76,   75,   76,   75,  265,   76,   76,   76,  117,  117,
      117,  122,  176,  122,   75,  263,  122,  122,  122,  261,
       75,  124,  124,  124,  125,  132,  125,  132,   75,  125,
      125,  125,  124,  124,  128,  128,  128,  165,  165,  129,
      129,  129,  258,  254,  132,  168,  168,  168,  253,  124,
      124,  129,  132,  165,  165,  165,  252,  169,  169,  169,
      170,  245,  170,  209,  209,  170,  170,  170,  129,  169,
      171,  171,  171,  172,  172,  172,  212,  212,  212,  209,
      209,  209,  213,  213,  213,  172,  169,  237,  242,  240,

      237,  240,  255,  256,  213,  255,  256,  259,  240,  259,
      267,  269,  172,  267,  269,  271,  259,  271,  278,  241,
      278,  213,  282,  283,  282,  283,  285,  239,  285,  238,
      235,  234,  232,  231,  230,  229,  228,  227,  225,  224,
      222,  221,  220,  219,  216,  211,  210,  206,  205,  204,
      202,  201,  200,  199,  198,  197,  196,  195,  194,  193,
      192,  278,  287,  287,  287,  287,  287,  287,  288,  288,
      189,  288,  288,  288,  289,  289,  291,  291,  291,  291,
      291,  291,  292,  292,  292,  292,  292,  292,  293,  293,
      293,  293,  293,  293,  294,  188,  294,  294,  294,  294,

      295,  295,  295,  185,  295,  295,  296,  184,  296,  296,
      296,  296,  297,  183,  297,  297,  297,  297,  182,  179,
      177,  167,  166,  164,  163,  162,  161,  160,  159,  158,
      157,  156,  155,  154,  153,  152,  151,  150,  148,  146,
      145,  144,  143,  142,  141,  139,  138,  137,  136,  135,
      119,  118,  112,  109,  108,  105,  103,  102,  100,   99,
       98,   97,   96,   95,   94,   93,   92,   91,   90,   89,
       88,   87,   84,   80,   70,   58,   47,   46,   45,   44,
       42,   41,   39,   34,   33,   32,   31,   25,   19,   14,
       11,    9,    7,    3,  286,  286,  286,  286,  286,  286,

      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#define INITIAL 0
/* -*-fundamental-*-
 * Authors:  Peter Holst Andersen (txix@diku.dk)
 *           Jens Peter Secher (jpsecher@diku.dk)
 *           Henning Makholm (makholm@diku.dk)
 * Content:  ANSI C lexer: 
 *
 * Copyright © 1998. The TOPPS group at DIKU, U of Copenhagen.
 * Redistribution and modification are allowed under certain
 * terms; see the file COPYING.cmix for details.
 */
#line 13 "lex.l"
    #include <stdarg.h>
    #include <stdlib.h>
    #include <strstream.h>
    #include "errno.h"
    #include "auxilary.h"
    #include "fileops.h"
    #include "parser.h"
    #include "gram-tab.h"
    #include "symboltable.h"
    #include "diagnostic.h"
    #include "options.h"
    #include "directives.h"

    #define yylval ccclval
    
    extern Scope<ObjectDecl> names;

    static int typedef_name(char *str);

#define YY_NO_UNPUT 1
#line 637 "temp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 48 "lex.l"


#line 794 "temp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 287 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 495 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 50 "lex.l"
{ return (AUTO); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 51 "lex.l"
{ return (BREAK); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 52 "lex.l"
{ return (CASE); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 53 "lex.l"
{ return (CHAR); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 54 "lex.l"
{ return (CONST); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 55 "lex.l"
{ return (CONTINUE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 56 "lex.l"
{ return (DEFAULT); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 57 "lex.l"
{ return (DO); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 58 "lex.l"
{ return (DOUBLE);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 59 "lex.l"
{ return (ELSE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 60 "lex.l"
{ return (ENUM); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 61 "lex.l"
{ return (EXTERN); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 62 "lex.l"
{ return (FLOAT);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 63 "lex.l"
{ return (FOR); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 64 "lex.l"
{ return (GOTO); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 65 "lex.l"
{ return (IF); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 66 "lex.l"
{ return (INT); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 67 "lex.l"
{ return (LONG); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 68 "lex.l"
{ return (REGISTER); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 69 "lex.l"
{ return (RETURN); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 70 "lex.l"
{ return (SHORT); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 71 "lex.l"
{ return (SIGNED); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 72 "lex.l"
{ return (SIZEOF); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 73 "lex.l"
{ return (STATIC); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 74 "lex.l"
{ return (STRUCT); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 75 "lex.l"
{ return (SWITCH); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 76 "lex.l"
{ return (TYPEDEF); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 77 "lex.l"
{ return (UNION); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 78 "lex.l"
{ return (UNSIGNED); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 79 "lex.l"
{ return (VOID); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 80 "lex.l"
{ return (VOLATILE); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 81 "lex.l"
{ return (WHILE); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 83 "lex.l"
{ yylval.str = strdup(yytext);
                          if (typedef_name(yytext))
			      return (TYPEDEFname);
                          else
			      return (IDENTIFIER); 
		 	}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 89 "lex.l"
{ char const *cp = yytext+6 ;
                          while(*cp != '(') cp++ ;
                          yylval.str = strdup(cp+1);
                          return CMIXTAG;
                        }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 94 "lex.l"
{ yylval.str = strdup(yytext); return (INTEGERconstant); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 96 "lex.l"
{ yylval.str = strdup(yytext); return (UINTEGERconstant); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 98 "lex.l"
{ yylval.str = strdup(yytext); return (LONGconstant); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 100 "lex.l"
{ yylval.str = strdup(yytext); return (ULONGconstant); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 102 "lex.l"
{ yylval.str = strdup(yytext); return (CHARACTERconstant); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 104 "lex.l"
{ yylval.str = strdup(yytext); return (FLOATINGconstant); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 106 "lex.l"
{ yylval.str = strdup(yytext); return (DOUBLEconstant); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 108 "lex.l"
{ yylval.str = strdup(yytext); return (STRINGliteral); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 110 "lex.l"
{ return (ELLIPSIS); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 111 "lex.l"
{ return (RSassign); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 112 "lex.l"
{ return (LSassign); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 113 "lex.l"
{ return (PLUSassign); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 114 "lex.l"
{ return (MINUSassign); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 115 "lex.l"
{ return (MULTassign); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 116 "lex.l"
{ return (DIVassign); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 117 "lex.l"
{ return (MODassign); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 118 "lex.l"
{ return (ANDassign); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 119 "lex.l"
{ return (ERassign); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 120 "lex.l"
{ return (ORassign); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 121 "lex.l"
{ return (RIGHTSHIFT); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 122 "lex.l"
{ return (LEFTSHIFT); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 123 "lex.l"
{ return (ICR); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 124 "lex.l"
{ return (DECR); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 125 "lex.l"
{ return (ARROW); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 126 "lex.l"
{ return (ANDAND); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 127 "lex.l"
{ return (OROR); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 128 "lex.l"
{ return (LESSEQUAL); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 129 "lex.l"
{ return (GREATEQUAL); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 130 "lex.l"
{ return (EQUAL); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 131 "lex.l"
{ return (NOTEQUAL); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 132 "lex.l"
{ return(';'); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 133 "lex.l"
{ return('{'); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 134 "lex.l"
{ return('}'); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 135 "lex.l"
{ return(','); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 136 "lex.l"
{ return(':'); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 137 "lex.l"
{ return('='); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 138 "lex.l"
{ return('('); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 139 "lex.l"
{ return(')'); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 140 "lex.l"
{ return('['); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 141 "lex.l"
{ return(']'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 142 "lex.l"
{ return('.'); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 143 "lex.l"
{ return('&'); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 144 "lex.l"
{ return('!'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 145 "lex.l"
{ return('~'); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 146 "lex.l"
{ return('-'); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 147 "lex.l"
{ return('+'); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 148 "lex.l"
{ return('*'); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 149 "lex.l"
{ return('/'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 150 "lex.l"
{ return('%'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 151 "lex.l"
{ return('<'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 152 "lex.l"
{ return('>'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 153 "lex.l"
{ return('^'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 154 "lex.l"
{ return('|'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 155 "lex.l"
{ return('?'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 157 "lex.l"
{ ccchere++; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 158 "lex.l"
{  }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 159 "lex.l"
{
    			  if (strlen(yytext) > 1024) {
                              Diagnostic(WARNING,ccchere)
                                 << "truncating filename (> 1024)";
			      yytext[1024] = 0;
			  }
                          {
                              int newlineno ;
                              char newfilename[1024] ;
    			      sscanf(yytext, "# %d \"%[^\"]",
                                   &newlineno, newfilename);
                              ccchere = newfilename ;
			      ccchere = newlineno ;
                          }
		        }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 174 "lex.l"
{ ccchere = atoi(yytext+2); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 175 "lex.l"
{{
                            const char *pc = yytext ;
                            while ( *pc != 'x' ) pc++ ;
                            JamInDirective(pc+1,ccchere) ;
                        }}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 180 "lex.l"
{{  const char *pc = yytext ;
                            while ( *pc != '#' ) pc++ ;
                            Diagnostic(WARNING,ccchere) << "ignoring " << pc ;
                        }}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 184 "lex.l"
{{  const char *pc = yytext ;
                            while ( *pc != 'o' ) pc++ ;
                            pc += 2 ;
                            while ( *pc == ' ' || *pc == '\t' ) pc++ ;
                            Diagnostic(ERROR,ccchere) << pc;
                        }}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 190 "lex.l"
{ Diagnostic(ERROR,ccchere) << "bad character '"
                                                    << (char)yytext[0] << '\'';
                        }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 194 "lex.l"
ECHO;
	YY_BREAK
#line 1400 "temp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 287 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 287 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 286);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p = yytext_ptr + offset;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 194 "lex.l"


static int typedef_name(char *str) {
    const ObjectDecl* t = names.lookup(str);
    if (t) {
        if (t->linkage == Typedef || t->linkage == AbstractType )
            return 1;
    }
    return 0;
}

LexerTracker ccchere;

int cccLexWrapper::InUse = 0 ;

void cccLexWrapper::Entry(Position &pos) {
    if ( InUse++ )
        Diagnostic(INTERNAL,pos) << "tried to reenter C scanner";
}

#define MAXCMD 2048

cccLexWrapper::cccLexWrapper
       (const char *filename,const char*cppargs,Position ref) :ok(0),f(NULL) {
    Entry(ref);

    // Check that the file exists.
    if (!CheckFile(filename)) {
        Diagnostic(ERROR,ref) << filename << " doesn't exist";
        return ;
    }

    // Make an executable command consisting of the C preprocessor
    // called with user definitions, include directories, and the set
    // of C files.
    char cmd[MAXCMD];
    ostrstream ost(cmd,MAXCMD);
    if ( getenv("CPP") )
        ost << getenv("CPP") ;
    else
        ost << CPP ;
    ost << " " << cppargs
        << " -D__CMIX=__CMIX -D__STDC__ -I" ;
    if ( getenv("CMIX_SHADOW_DIR") )
	ost << getenv("CMIX_SHADOW_DIR") ;
    else
        ost << CMIX_SHADOW_DIR ;
    ost << ' ' << filename << ends;
    if (ost.fail()) {
        Diagnostic(ERROR,ref)
            << "CPP command too large. Enlarge MAXCMD in parser.cc";
        return ;
    }

    if ( trace_c_parser )
	cerr << cmd << endl ;
    // Use the C preprocessor as a filter. Its output is passed to the lexer.
    f = popen(cmd, "r");
    if (f == NULL) {
        Diagnostic d(ERROR,ref);
        d << "failed to spawn preprocessor with popen()";
	d.addline() << strerror(errno) ;
        d.addline() << "command was: " << cmd ;
        return ;
    }
    if ( only_preprocess_mode ) {
      int c ;
      cout << "/* C-MIX/II PREPROCESSED: " << filename << " */\n" ;
      while( (c=getc(f)) != EOF )
          cout << (unsigned char)c;
    } else  {
        yy_switch_to_buffer(yy_create_buffer(f,YY_BUF_SIZE)) ;
        ccchere = filename ;
        ccchere = 1 ;
        ok = 1 ;
    }
}

void cccLexWrapper::parse() {
    if ( ok )
        parser.ParseNow();
}

cccLexWrapper::~cccLexWrapper() {
  if ( ok )
    yy_delete_buffer(YY_CURRENT_BUFFER);
  if ( f )
    if ( pclose(f) != 0 )
      Diagnostic(ERROR,Position()) << "preprocessor failed" ;
  InUse-- ;
}
